// Auto-generated by add_indices.py
import AbstractInnerPage from "./AbstractInnerPage";
import CandidatePage from "./CandidatePage";
import CriteriaPage from "./CriteriaPage";
import HomePage from "./HomePage";
import PAGE_CONFIG_LIST from "./PAGE_CONFIG_LIST";

export {
  AbstractInnerPage,
  CandidatePage,
  CriteriaPage,
  HomePage,
  PAGE_CONFIG_LIST,
};
