// Auto-generated by add_indices.py
import AbstractInnerPage from "./AbstractInnerPage";
import AbstractStepPage from "./AbstractStepPage";
import CandidatePage from "./CandidatePage";
import CriteriaPage from "./CriteriaPage";
import GroundTruthPage from "./GroundTruthPage";
import HomePage from "./HomePage";
import PAGE_CONFIG_LIST from "./PAGE_CONFIG_LIST";
import StartPage from "./StartPage";

export {
  AbstractInnerPage,
  AbstractStepPage,
  CandidatePage,
  CriteriaPage,
  GroundTruthPage,
  HomePage,
  PAGE_CONFIG_LIST,
  StartPage,
};
