// Auto-generated by add_indices.py
import Candidate from "./Candidate";
import Criterion from "./Criterion";
import GroundTruth from "./GroundTruth";
import Party from "./Party";
import Version from "./Version";
import Weight from "./Weight";

export { Candidate, Criterion, GroundTruth, Party, Version, Weight };
