
import os
import json
from openpyxl import load_workbook
from utils import File, Log

log = Log('gen_criterion_to_candidate_to_weight')

def main():
    wb = load_workbook(os.path.join(
        "data", "Candidates.xlsx"
    ))
    ws = wb['Criterion x Candidate']
    idx = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        criterionID, candidateID, weight, refs = row
        if not criterionID:
            continue
        if criterionID not in idx:
            idx[criterionID] = {}
        idx[criterionID][candidateID] = dict(
            weight=weight,
            refs=refs,
        )

    lines = ['// Auto Generated by gen_criterion_to_candidate_to_weight.py', 'export const CRITERION_TO_CANDIDATE_TO_WEIGHT = ' + json.dumps(idx, indent=2) + ';',  '']
   
    js_path = os.path.join("src", "nonview", "data", "CRITERION_TO_CANDIDATE_TO_WEIGHT.js")
    File(js_path).write_lines(lines)
    log.info(f'Wrote {js_path}')

if __name__ == "__main__":
    main()