
import os
import json
from openpyxl import load_workbook
from utils import File, Log

log = Log('gen_criterion_to_candidate_to_score')

def main():
    wb = load_workbook(os.path.join(
        "data", "Candidates.xlsx"
    ))
    ws = wb['Criterion x Candidate']
    idx = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        ___, criterionDetails, ___, candidateID, score, ___ = row
        if not criterionDetails:
            continue
        if criterionDetails not in idx:
            idx[criterionDetails] = {}
        idx[criterionDetails][candidateID] = score

    lines = ['// Auto Generated by gen_criterion_to_candidate_to_score.py', 'export const CRITERION_TO_CANDIDATE_TO_SCORE = ' + json.dumps(idx, indent=2) + ';',  '']
   
    js_path = os.path.join("src", "nonview", "data", "CRITERION_TO_CANDIDATE_TO_SCORE.js")
    File(js_path).write_lines(lines)
    log.info(f'Wrote {js_path}')

if __name__ == "__main__":
    main()