import os
import json
from openpyxl import load_workbook
from utils import File, Log

log = Log("gen_candidates")


def get_candidate_d_list():
    wb = load_workbook(os.path.join("data", "Candidates.xlsx"))
    ws = wb["Candidates"]
    d_list = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        (
            regNum,
            regDate,
            id,
            firstNameShort,
            firstNames,
            lastName,
            gender,
            party,
            support,
            imgFile,
            xHandle,
            wikipediaPage,
            parliamentNum,
            linkedInID,
            manthriLKID,
        ) = row
        d = dict(
            regNum=regNum,
            regDate=str(regDate)[:10],
            id=id,
            firstNameShort=firstNameShort,
            firstNames=firstNames,
            lastName=lastName,
            gender=gender,
            party=party,
            support=support,
            imgFile=imgFile,
            xHandle=xHandle,
            wikipediaPage=wikipediaPage,
            parliamentNum=parliamentNum,
            linkedInID=linkedInID,
            manthriLKID=manthriLKID,
        )

        d_list.append(d)
    d_list.sort(key=lambda d: d["id"])
    return d_list


def main():
    d_list = get_candidate_d_list()
    lines = [
        "// Auto Generated by gen_candidates.py",
        "export const CANDIDATE_D_LIST = [",
    ]
    for d in d_list:
        lines.append(json.dumps(d, indent=2) + ",")
    lines.extend(["];", ""])

    js_path = os.path.join("src", "nonview", "data", "CANDIDATE_D_LIST.js")
    File(js_path).write_lines(lines)
    log.info(f"Wrote {js_path}")


if __name__ == "__main__":
    main()
