
import os
import json
from openpyxl import load_workbook
from utils import File, Log

log = Log('gen_candidates')

def main():
    wb = load_workbook(os.path.join(
        "data", "Candidates.xlsx"
    ))
    ws = wb['Candidates']
    lines = ['// Auto Generated by gen_candidates.py', 'export const CANDIDATE_D_LIST = [']
    for row in ws.iter_rows(min_row=2, values_only=True):
        id, firstName, lastName, party, imgFile, xHandle, wikipediaPage, parliamentNum = row
        d = dict(
            id=id,
            firstName=firstName,
            lastName=lastName,
            party=party,
            imgFile=imgFile,
            xHandle=xHandle,
            wikipediaPage=wikipediaPage,
            parliamentNum=parliamentNum,
        )
        lines.append(json.dumps(d, indent=2) + ',')
    lines.extend(['];', ''])

    js_path = os.path.join("src", "nonview", "data", "CANDIDATE_D_LIST.js")
    File(js_path).write_lines(lines)
    log.info(f'Wrote {js_path}')

if __name__ == "__main__":
    main()