
import os
from openpyxl import load_workbook
from utils import File, Log
import json
log = Log('gen_criteria')

def main():
    wb = load_workbook(os.path.join(
        "data", "Candidates.xlsx"
    ))
    ws = wb['Criteria']
    lines = ['// Auto Generated by gen_criteria.py', 'export const CRITERION_D_LIST = [']
    for row in ws.iter_rows(min_row=2, values_only=True):
        id, details, refs = row
        d = dict(
            id=id,
            details=details,
            refs=refs,
        )
        lines.append(json.dumps(d, indent=2) + ',')
    lines.extend(['];', ''])

    js_path = os.path.join("src", "nonview", "data", "CRITERION_D_LIST.js")
    File(js_path).write_lines(lines)
    log.info(f'Wrote {js_path}')

if __name__ == "__main__":
    main()