
import os
from openpyxl import load_workbook
from utils import File, Log

log = Log('gen_criteria')

def main():
    wb = load_workbook(os.path.join(
        "data", "Candidates.xlsx"
    ))
    ws = wb['Criteria']
    lines = ['// Auto Generated by gen_criteria.py', 'export const CRITERION_LIST = [']
    for row in ws.iter_rows(min_row=2, values_only=True):
        lines.append(f'  "{row[1]}",')
    lines.extend(['];', ''])

    js_path = os.path.join("src", "nonview", "data", "CRITERION_LIST.js")
    File(js_path).write_lines(lines)
    log.info(f'Wrote {js_path}')

if __name__ == "__main__":
    main()