
import os
import json
from openpyxl import load_workbook
from utils import File, Log

from gen_candidates import get_candidate_d_list
from gen_criteria import get_criterion_d_list

log = Log('gen_criterion_to_candidate_to_weight_info')


DEFAULT_WEIGHT_INFO = dict(
    weight=0,
    refs='',
)

def get_idx():
    wb = load_workbook(os.path.join(
        "data", "Candidates.xlsx"
    ))
    ws = wb['Criterion x Candidate']
    idx = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        criterionID, candidateID, weight, refs = row
        if not criterionID:
            continue
        if criterionID not in idx:
            idx[criterionID] = {}
        idx[criterionID][candidateID] = dict(
            weight=weight,
            refs=refs,
        )
    return idx

def expand_idx(idx):
    candidate_d_list = get_candidate_d_list()
    criterion_d_list = get_criterion_d_list()

    for criterion_d in criterion_d_list:
        criterionID = criterion_d['id']
        if criterionID not in idx:
            idx[criterionID] = {}
        for candidate_d in candidate_d_list:
            candidateID = candidate_d['id']
            if candidateID not in idx[criterionID]:
                idx[criterionID][candidateID] = DEFAULT_WEIGHT_INFO
    return idx

def write_idx(idx):
    wb = load_workbook(os.path.join(
        "data", "Candidates.xlsx"
    ))
    ws = wb['Criterion x Candidate']
    ws.delete_rows(2, ws.max_row)
    for criterionID, candidate_to_weight in sorted(idx.items(), key=lambda x: x[0]):
        for candidateID, weight_info in sorted(candidate_to_weight.items(), key=lambda x: x[0]):
            ws.append([criterionID, candidateID, weight_info['weight'], weight_info['refs']])
    wb.save(os.path.join("data", "Candidates.xlsx"))

def main():
    idx = get_idx()
    idx = expand_idx(idx)
    write_idx(idx)

    lines = ['// Auto Generated by gen_criterion_to_candidate_to_weight.py', 'export const CRITERION_TO_CANDIDATE_TO_WEIGHT = ' + json.dumps(idx, indent=2) + ';',  '']
   
    js_path = os.path.join("src", "nonview", "data", "CRITERION_TO_CANDIDATE_TO_WEIGHT.js")
    File(js_path).write_lines(lines)
    log.info(f'Wrote {js_path}')

if __name__ == "__main__":
    main()