// Auto-generated by add_indices.py
import AlignCenter from "./AlignCenter";
import AlignRight from "./AlignRight";
import GoogleSearchView from "./GoogleSearchView";
import ParliamentView from "./ParliamentView";
import TimeView from "./TimeView";
import WikipediaPageView from "./WikipediaPageView";
import XHandleView from "./XHandleView";

export {
  AlignCenter,
  AlignRight,
  GoogleSearchView,
  ParliamentView,
  TimeView,
  WikipediaPageView,
  XHandleView,
};
